# Generated by Django 2.2.1 on 2019-10-04 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome do departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128, verbose_name='Titulo')),
                ('conteudo', models.TextField(verbose_name='Conteudo')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=50, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('data_criacao', models.DateField(blank=True, null=True, verbose_name='Data de criação')),
                ('interessados', models.ManyToManyField(related_name='pessoa', to='app_processo.Pessoa')),
                ('investigados', models.ManyToManyField(related_name='pessoa1', to='app_processo.Pessoa')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_processo.Pessoa')),
                ('matricula', models.CharField(max_length=50, verbose_name='Matricula')),
            ],
            bases=('app_processo.pessoa',),
        ),
        migrations.CreateModel(
            name='PedidoDePrazo',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_processo.Documento')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('data_nova', models.DateField(blank=True, null=True, verbose_name='Novo prazo')),
            ],
            bases=('app_processo.documento',),
        ),
        migrations.CreateModel(
            name='PortariaDeInstauracao',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_processo.Documento')),
            ],
            bases=('app_processo.documento',),
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_tramite', models.DateField(blank=True, null=True, verbose_name='Data do tramite')),
                ('departamento_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamento1', to='app_processo.Departamento')),
                ('departamento_inicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamento2', to='app_processo.Departamento')),
                ('processo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo.Processo')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='processo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo.Processo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo.Funcionario', verbose_name='Funcionario'),
        ),
        migrations.CreateModel(
            name='EnvioDeProcesso',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_processo.Documento')),
                ('data_envio', models.DateField(blank=True, null=True, verbose_name='Data de envio')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamento', to='app_processo.Departamento')),
            ],
            bases=('app_processo.documento',),
        ),
    ]
